apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: "2019-09-25T19:33:07Z"
  labels:
    controller-uid: 4ce10632-dfcb-11e9-939e-4201ac100003
    job-name: istio-init-crd-11
  name: istio-init-crd-11
  namespace: istio-system
  resourceVersion: "1833"
  selfLink: /apis/batch/v1/namespaces/istio-system/jobs/istio-init-crd-11
  uid: 4ce10632-dfcb-11e9-939e-4201ac100003
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 4ce10632-dfcb-11e9-939e-4201ac100003
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        controller-uid: 4ce10632-dfcb-11e9-939e-4201ac100003
        job-name: istio-init-crd-11
    spec:
      containers:
      - command:
        - kubectl
        - apply
        - -f
        - /etc/istio/crd-11/crd-11.yaml
        image: docker.io/istio/kubectl:1.2.5
        imagePullPolicy: IfNotPresent
        name: istio-init-crd-11
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/istio/crd-11
          name: crd-11
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: istio-init-service-account
      serviceAccountName: istio-init-service-account
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: istio-crd-11
        name: crd-11
status:
  completionTime: "2019-09-25T19:33:20Z"
  conditions:
  - lastProbeTime: "2019-09-25T19:33:20Z"
    lastTransitionTime: "2019-09-25T19:33:20Z"
    status: "True"
    type: Complete
  startTime: "2019-09-25T19:33:07Z"
  succeeded: 1